security:
    token: 04323fe3a8b5bcab5eb730e7deeccd87eb823f05
    enable_registration: true
    enable_login: true
    login_required_to_edit_gist: true
    login_required_to_view_gist: false
    login_required_to_view_embeded_gist: false
api:
    enabled: true
    api_key_required: true
    base_url: 'https://ccp.ooo'
    client: { api_key: 2ERdGQAu9gOX00EgZ4ooPi1QJkqSCltrhlKSNVsV }
data:
    path: data/git
git:
    path: /usr/bin/git
theme:
    name: dark

