security:
    token: 34a18c89d8995c3452cdd78ffe08fe133f32eea4
    enable_registration: true
    enable_login: true
    login_required_to_edit_gist: true
    login_required_to_view_gist: false
    login_required_to_view_embeded_gist: false
api:
    enabled: true
    api_key_required: true
    base_url: 'https://EXAMPLE.com'
    client: { api_key: GDP7knrm5xjlASm31Svw21Cn989P0PplTyMQ }
data:
    path: /data/gistpb/data/git
git:
    path: /usr/bin/git
theme:
    name: dark

